# Generated by Django 6.0.7 on 2026-07-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_alter_word_word'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['word']},
        ),
        migrations.CreateModel(
            name='WordSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True)),
                ('num_chars', models.PositiveIntegerField()),
                ('num_words', models.PositiveIntegerField()),
                ('words', models.ManyToManyField(to='words.word')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
