# Generated by Django 6.0.7 on 2026-07-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_alter_word_options_wordset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wordset',
            name='num_chars',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wordset',
            name='num_words',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wordset',
            name='words',
            field=models.ManyToManyField(null=True, to='words.word'),
        ),
    ]
