# Generated by Django 6.0.7 on 2026-07-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_alter_word_active_alter_wordset_num_chars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordset',
            name='words',
            field=models.ManyToManyField(to='words.word'),
        ),
    ]
