# Generated by Django 6.0.7 on 2026-07-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_alter_wordset_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordset',
            name='num_chars',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wordset',
            name='num_words',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
