# Generated by Django 6.0.7 on 2026-07-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_alter_wordset_num_chars_alter_wordset_num_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordset',
            name='num_chars',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wordset',
            name='num_words',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
