# Generated by Django 6.0.7 on 2026-07-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_alter_wordset_num_chars_alter_wordset_num_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordset',
            name='words',
            field=models.ManyToManyField(blank=True, to='words.word'),
        ),
    ]
