# Generated by Django 6.0.7 on 2026-07-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_alter_wordset_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
